from pathlib import Path
from typing import Protocol


class FileStore(Protocol):
    def session_video_path(self, session_id: str) -> Path: ...
    def upload_path(self, filename: str) -> Path: ...
    def report_path(self) -> Path: ...
