from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path
from typing import Protocol

from deep_sea_explorer.domain.models import CaptureDecision, ModelHealth, StreamEvent
from deep_sea_explorer.services.key_frame_detection import SurveyEventEvaluation


class VisionModelGateway(Protocol):
    def health(self) -> ModelHealth: ...
    def describe_video(self, video_path: Path) -> str: ...
    def evaluate_frame(self, image_path: Path) -> CaptureDecision: ...
    def answer(self, video_path: Path, question: str) -> Iterator[StreamEvent]: ...
    def summarize_report(self, material: dict[str, object]) -> str: ...
    def evaluate_survey_event(
        self, reference_image: Path | None, current_image: Path, metadata: dict[str, object]
    ) -> SurveyEventEvaluation: ...


class ImageGenerationGateway(Protocol):
    def generate(self, prompt: str) -> bytes: ...
